weather_codes = {
    0: ["🌞", "Clear sky"],
    1: ["🌤️", "Mainly clear"],
    2: ["⛅", "Partly cloudy"],
    3: ["☁️", "Overcast"],
    45: ["🌫️", "Fog"],
    48: ["🌫️", "Depositing rime fog"],
    51: ["🌧️", "Light Drizzle"],
    53: ["🌧️", "Moderate Drizzle"],
    55: ["🌧️", "Dense Drizzle"],
    56: ["🌨️", "Light Freezing drizzle"],
    57: ["🌨️", "Dense Freezing drizzle"],
    61: ["🌦️", "Light Rain"],
    63: ["🌦️", "Moderate Rain"],
    65: ["🌧️", "Heavy Rain"],
    66: ["🌨️", "Light Freezing rain"],
    67: ["🌨️", "Heavy Freezing rain"],
    71: ["❄️", "Light Snow fall"],
    73: ["❄️", "Moderate Snow fall"],
    75: ["❄️", "Heavy Snow fall"],
    77: ["❄️", "Snow grains"],
    80: ["🌧️", "Light Rain showers"],
    81: ["🌧️", "Moderate Rain showers"],
    82: ["🌧️", "Violent Rain showers"],
    85: ["❄️", "Slight Snow showers"],
    86: ["❄️", "Heavy Snow showers"],
    95: ["⚡", "Slight Thunderstorm"],
    96: ["⚡", "Thunderstorm with hail"],
    99: ["⚡", "Thunderstorm with hail"]
}